---
abstract: 'Template Toolkit plugin for encoding and decoding International Domain Names.'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Template::Test: '0'
  Test::More: '0'
  perl: '5.008'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Plugin-Filter-IDN
provides:
  Template::Plugin::Filter::IDN:
    file: lib/Template/Plugin/Filter/IDN.pm
    version: '0.04'
requires:
  Carp: '0'
  List::Util: '1.33'
  Net::IDN::Encode: '0'
  Template::Plugin::Filter: '0'
  parent: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mschout/perl-template-plugin-filter-idn/issues
  homepage: https://github.com/mschout/perl-template-plugin-filter-idn
  repository: https://github.com/mschout/perl-template-plugin-filter-idn.git
version: '0.04'
x_serialization_backend: 'YAML::Tiny version 1.70'
